apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-sample
  labels:
    app: api-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api-sample

  template:
    metadata:
      labels:
        app: api-sample
    
    spec:
      containers:
        - name: api-sample
          image: weihanli/api-sample:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
